# This file generates the GitHub Actions matrix.
---
include:
  # Keyboard: Ferris Sweep (Left / Central)
  - board: nice_nano@2
    shield: cradio_left
    snippet: studio-rpc-usb-uart
    artifact-name: sweep_left
    # snippet: zmk-usb-logging
    
  # Keyboard: Ferris Sweep (Right / Peripheral)
  - board: nice_nano@2
    shield: cradio_right
    artifact-name: sweep_right
  
  # Settings Reset (The "Nuclear" Fix for Bluetooth)
  - board: nice_nano@2
    shield: settings_reset
    artifact-name: sweep_settings_reset
